// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Infra.Database;

#nullable disable

namespace OnlineStore.Infra.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop products",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mobile Products",
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Accessories Products",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "asus_g15.jpg",
                            FilePath = "/images/products/asus_g15.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            FileName = "macbook_air_m1.jpg",
                            FilePath = "/images/products/macbook_air_m1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            FileName = "dell_xps13.jpg",
                            FilePath = "/images/products/dell_xps13.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            FileName = "hp_pavilion15.jpg",
                            FilePath = "/images/products/hp_pavilion15.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            FileName = "lenovo_legion5.jpg",
                            FilePath = "/images/products/lenovo_legion5.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            FileName = "samsung_s23.jpg",
                            FilePath = "/images/products/samsung_s23.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            FileName = "iphone14.jpg",
                            FilePath = "/images/products/iphone14.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            FileName = "redmi_note12.jpg",
                            FilePath = "/images/products/redmi_note12.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            FileName = "pixel7.jpg",
                            FilePath = "/images/products/pixel7.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            FileName = "nokia_x20.jpg",
                            FilePath = "/images/products/nokia_x20.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            FileName = "mx_master3s.jpg",
                            FilePath = "/images/products/mx_master3s.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            FileName = "airpods_pro2.jpg",
                            FilePath = "/images/products/airpods_pro2.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            FileName = "anker_20k.jpg",
                            FilePath = "/images/products/anker_20k.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            FileName = "sony_ch710n.jpg",
                            FilePath = "/images/products/sony_ch710n.jpg",
                            ProductId = 14
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Gaming Laptop Ryzen 7, RTX 3060",
                            Price = 52000m,
                            Stock = 10,
                            Title = "Laptop Asus ROG Strix G15"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple M1, 8GB RAM, 256GB SSD",
                            Price = 45000m,
                            Stock = 12,
                            Title = "Laptop Apple MacBook Air M1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Core i7, 16GB RAM, 512GB SSD",
                            Price = 58000m,
                            Stock = 8,
                            Title = "Laptop Dell XPS 13"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Core i5, 8GB RAM, 256GB SSD",
                            Price = 28000m,
                            Stock = 15,
                            Title = "Laptop HP Pavilion 15"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Ryzen 7, RTX 3050",
                            Price = 49000m,
                            Stock = 9,
                            Title = "Laptop Lenovo Legion 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Flagship Snapdragon 8 Gen2",
                            Price = 34000m,
                            Stock = 20,
                            Title = "Samsung Galaxy S23"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "128GB, Super Retina XDR",
                            Price = 42000m,
                            Stock = 17,
                            Title = "Apple iPhone 14"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Great mid-range, 120Hz",
                            Price = 11000m,
                            Stock = 30,
                            Title = "Xiaomi Redmi Note 12"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Tensor G2, Amazing Camera",
                            Price = 28000m,
                            Stock = 12,
                            Title = "Google Pixel 7"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Reliable with clean Android",
                            Price = 9000m,
                            Stock = 18,
                            Title = "Nokia X20"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Ergonomic Wireless Mouse",
                            Price = 3500m,
                            Stock = 22,
                            Title = "Logitech MX Master 3S"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "ANC, Spatial Audio",
                            Price = 9500m,
                            Stock = 15,
                            Title = "Apple AirPods Pro 2"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "High-capacity Power Bank",
                            Price = 1800m,
                            Stock = 25,
                            Title = "Anker PowerCore 20k"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Noise Cancelling Wireless",
                            Price = 3800m,
                            Stock = 14,
                            Title = "Sony WH-CH710N Headphones"
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 300000m,
                            Password = "123",
                            Role = 1,
                            Username = "ali"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 500000m,
                            Password = "zk123",
                            Role = 0,
                            Username = "zahra.k"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 400000m,
                            Password = "1234",
                            Role = 0,
                            Username = "sahar"
                        });
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.CartItem", b =>
                {
                    b.HasOne("OnlineStore.Domain.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Domain.Core.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Image", b =>
                {
                    b.HasOne("OnlineStore.Domain.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Order", b =>
                {
                    b.HasOne("OnlineStore.Domain.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineStore.Domain.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.Domain.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Product", b =>
                {
                    b.HasOne("OnlineStore.Domain.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("OnlineStore.Domain.Core.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
